name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 */12 * * *" # runs at every 12AM UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          LANG_COUNT: 8
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true
          COMMIT_MESSAGE: Update waka-readme
